### PR TITLE
OkHttpRequestor: Clean up default settings helpers.

### PR DESCRIPTION
**Pull request by cakoose**
Deprecate the INSTANCE field.  It depends on SSLConfig, which has an
expensive initializer.  Some clients don't use SSLConfig, so don't make
them pay the initialization costs.

Make defaultOkHttpClient() public as a replacement.

Deprecate getClient().  Seems unnecessary so let's reduce the API
surface.

@zjiuyang @scottbez1

### CODE REVIEW

**Comment by zjiuyang** [comment]
I see the reason for doing this. Can we use some lazy initialization to keep the getClient() instead of planing to removing it?

**Comment by cakoose** [comment]
The `getClient()` removal wasn't about initialization cost.  It was just that it seemed like an unnecessary API.

For example, if you want to have access to the `OkHttpClient` instance, you can just keep track of that (instead of keeping track of the `OkHttpRequestor` wrapper and pulling the `OkHttpClient` instance out of that).

**Comment by cakoose** [comment]
Lemme separate the `getClient()` deprecation into a different diff.

**Comment by zjiuyang** [comment]
LGTM

**Pull request closed without merging**
