### PR TITLE
Gradle updated and convert example to androidX

### PR DESCRIPTION
**Pull request by AliAzaz**
updated dependencies and gradle version. Also, converted android example to AndroidX.

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks for putting this together!

**Comment by AliAzaz** [comment]
Could you please approve this PR

**Comment by greg-db** [comment]
@AliAzaz I've asked the team to review this, but I can't promise a timeline for that.

**Comment by greg-db** [comment]
We've merged https://github.com/dropbox/dropbox-sdk-java/pull/273 and released [v3.1.4](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.1.4). I believe that should cover this PR as well, but let us know if there's anything here not covered by that. Thanks!

**Pull request closed without merging**
